
--QUERYBUILDER http://serwer-bo1:8080/AdminTools/querybuilder/ie.jsp

--lastlogon user

SELECT  SI_ID, SI_NAME, SI_USERFULLNAME, SI_DESCRIPTION, SI_LASTLOGONTIME, SI_CREATION_TIME FROM CI_APPOBJECTS, CI_SYSTEMOBJECTS, CI_INFOOBJECTS 
WHERE SI_NAME NOT IN ('ADMINISTRATOR','GUEST') AND SI_KIND='USER'
AND SI_LASTLOGONTIME < '2018.11.25' ORDER BY SI_NAME 

--loggednever

SELECT TOP 5000 SI_NAME, SI_LASTLOGONTIME FROM CI_SYSTEMOBJECTS
WHERE SI_NAME NOT IN ('ADMINISTRATOR','GUEST') AND SI_KIND='USER'
AND SI_LASTLOGONTIME IS NULL ORDER BY SI_NAME